behaviors:
  PRV_Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5000000
    time_horizon: 256
    summary_freq: 10000

environment_parameters:
  area_size:
    curriculum:
      - name: MapSizeCurriculum
        completion_criteria:
          measure: reward
          behavior: PRV_Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 10.0 
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: PRV_Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 15.0
      - name: Lesson2
        value: 20.0

  episode_duration:
    curriculum:
      - name: DurationCurriculum
        completion_criteria:
          measure: reward
          behavior: PRV_Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 20.0
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: PRV_Agent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 30.0
      - name: Lesson2
        value: 45.0