behaviors:
  CubeAgent:
    trainer_type: ppo
    hyperparameters:
        batch_size: 2048
        beta: 5.0e-3
        buffer_size: 20480
        epsilon: 0.2
        lambd: 0.95
        learning_rate: 3.0e-4
        learning_rate_schedule: linear
        num_epoch: 3
    network_settings:
        hidden_units: 256
        normalize: false
        num_layers: 2
        vis_encode_type: simple
        memory:
            memory_size: 128
            sequence_length: 64
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    max_steps: 5.0e6
    time_horizon: 128
    summary_freq: 10000
    